project: "TEST_01"
meta: "/scratch/devel/mdabad/DEVEL/snakemake/TEST/rnapipeline/meta.tsv"

# Mapping parameters
paired: false
map_mode: "bulk"
mode: "small"
strand: "forw"
trimming: true
index:
  star: "path/index"
  rsem: "path/index"
  gtf: "path/file.gtf"
versions:
  star_version: "2.7.8a"
  rsem_version: "1.3.0"
path:
  trim: "/tmp"
  map: "/tmp"
  quant: "/tmp"
  dge: "/home/joan/Test"

# DGEA parameters
# Method to use. Either "limma" or "deseq2"
dge_method: "limma"
# Path to the files
info: "/home/joan/OneDrive/UOC/TFM/testdata/prova_grups/info_10.txt" #"/home/joan/OneDrive/UOC/TFM/testdata/info_3.txt" #
counts: "/home/joan/OneDrive/UOC/TFM/testdata/prova_grups/counts_10.txt" #"/home/joan/OneDrive/UOC/TFM/testdata/counts_3.txt" #
# Lists of covariants to include (or NULL).
factors: ["MOTHER","DIET","CONDITION","GROUP"] #["CODE","GENE","SEX","GROUP"] #
continuous: []
n_continuous_splits: [3]
# Variable that contains the groups
group: "GROUP"
# group: "GROUP_DUMMY"
# Control group
control: "Unaffected"
# Only PCA should be generated? (Boolean)
onlypca: false
# String with the formula to use for the model
formula: "~0+group" #"~SEX+group"  #
# Each contrast
contrasts:
  # DESeq2 example
  # affected_vs_unaffected:
  #   - Affected
  #   - Unaffected
  # mild_vs_unaffected: 
  #   - Mild
  #   - Unaffected
  # severe_vs_unaffected:
  #   - Severe
  #   - Unaffected
  # mild_vs_severe:
  #   - Mild
  #   - Severe

  # limma example
  # affected_vs_unaffected: Affected - Unaffected
  affected_D_vs_unaffected_D: "affected_D - control_D"
  affected_N_vs_unaffected_N: "affected_N - control_N"
  affected_E_vs_unaffected_E: "affected_E - control_E"
  D_vs_E_int: "(affected_D - control_D) - (affected_E - control_E)"
  D_vs_N_int: "(affected_D - control_D) - (affected_N - control_N)"
  N_vs_E_int: "(affected_N - control_N) - (affected_E - control_E)"

# Interaction identifier (Only for limma): A string (either "int", "diff" or something else)
interaction_id: "int"
# Shrinkage method (ONLY DESeq2: either "normal" or "ashr". "apeglm" not implemented)
shrinkage_method: "normal"

## Pathway analysis params
# Method: Either "gprofiler", "fgsea" or "both"
pathway_method: "both"
# Species
species: "Oryctolagus cuniculus" #"Homo sapiens" #
## ORA params
# Base URL
baseurl: "https://biit.cs.ut.ee/gprofiler"
# Translate gene ID to orthologous target species. False or the species.
orth_species: false
## FGSEA params
# GMT file: Absolute path to the environment or blank for automatic Reactome pathways.
gmt: "/home/joan/OneDrive/UOC/TFM/testdata/Ensembl2Reactome.HSA.gmt"
# Gene identifier to use in the GSEA ("ENSEMBL","SYMBOL")
id_type: "patata"
# Rank column number or name. If blank, defaults to "stat" for DESeq2, and "t" for limma.
rank:

## Plotting
# Whether plots shall be generated
plot: true
# Whether high quality TIFF plots should be generated
tiff: true
# Specify plot atributes
plot_atr:
  # Can I make this a list so it makes several PCA?
  pca: "group"
  heatmap_ann: "group"
  # Number of genes to show in the heatmap
  de_genes_n: 50