project: "TEST_01"
meta: "/home/joan/OneDrive/UOC/TFM/snakemake-workflow-cnag/test.tsv"

# Mapping parameters
paired: false
map_mode: "bulk"
mode: "small"
strand: "forw"
trimming: true
index:
  star: "path/index"
  rsem: "path/index"
  gtf: "path/file.gtf"
versions:
  star_version: "2.7.8a"
  rsem_version: "1.3.0"
path:
  trim: "/tmp"
  map: "/tmp"
  quant: "/tmp"
  pca: "~/Test"

# DESeq2 parameters
# Lists of covariants to include (or NULL).
factors: ["CODE","GENE","SEX","GROUP","GROUP_DUMMY"]
continuous: ["CONTINUA1","CONTINUA2"]
# Variable that contains the groups
group: "GROUP_DUMMY"
# group: "GROUP_DUMMY"
# Control group
control: "Unaffected"
# Only PCA should be generated? (Boolean)
onlypca: False
# String with the formula to use for the model
formula: "~SEX + group"
# Each contrast as a list (variable, experimental group, control group)
contrasts:
  #affected_vs_unaffected: 
  #  - Affected
  #  - Unaffected
  mild_vs_unaffected: 
    - Mild
    - Unaffected
  severe_vs_unaffected:
    - Severe
    - Unaffected
  mild_vs_severe:
    - Mild
    - Severe

# Shrinkage method (either "normal" or "ashr". "apeglm" not implemented)
shrinkage_method: "ashr"
# Whether plots shall be generated
plot: True
# Specify plot atributes
plot_atr:
  # Can I make this a list so it makes several PCA? It seems slow.
  pca: "SEX"
  heatmap_ann: "group"
  # Number of genes to show in the heatmap
  de_genes_n: 50
# Dir where to create the results folder
directory: "~/Test"