project: "TEST_01"
meta: "/home/joan/OneDrive/UOC/TFM/snakemake-workflow-cnag/test.tsv"

# Mapping parameters
paired: false
map_mode: "bulk"
mode: "small"
strand: "forw"
trimming: true
index:
  star: "path/index"
  rsem: "path/index"
  gtf: "path/file.gtf"
versions:
  star_version: "2.7.8a"
  rsem_version: "1.3.0"
path:
  trim: "/tmp"
  map: "/tmp"
  quant: "/tmp"

# DESeq2 parameters
# Specify a list with the covariants to include
factors: ["SEX"]
continuous: [NULL]
# Specify which variable contains the groups
group: "GROUP"
# Specify the control group
control: "Unaffected"
# Specify if only PCA should be generated
onlypca: False
# Specify a string with the formula to use for the model
formula: "~SEX + group"
# Specify the contrasts as a list
contrast:
  affected_vs_unaffected: ["group","Affected","Unaffected"]
# Whether plots shall be generated
plot: True

# Specify plot atributes
plot_atr:
  pca: "group"
  heatmap_ann: "group"
  # Numbern of genes to show in the heatmap
  de_genes_n: 50