project: "TEST_01"

path:
  trim: "/tmp"
  map: "/tmp"
  quant: "/tmp"
  dge: "/home/joan/Test"

# DEG Parameters
# Lists of covariants to include (or NULL).
factors: ["MOTHER","DIET","CONDITION","GROUP"]
continuous: []
# Splits to perform to the continuous variable to factorize it
n_continuous_splits: [3]
# Variable that contains the groups
group: "GROUP"
# group: "GROUP_DUMMY"
# Control group (only DESeq2)
control: 
# Only PCA should be generated? (Boolean)
onlypca: false
# String with the formula to use for the model
formula: "~0+group"
# Each contrast (different for DESeq2 and Limma)
contrasts:
# DESeq2 example
  # affected_vs_unaffected_D:
  #   - affected_D
  #   - control_D
  # affected_vs_unaffected_N:
  #   - affected_N
  #   - control_N
  # affected_vs_unaffected_E:
  #   - affected_E
  #   - control_E

# limma example
  affected_vs_unaffected_D: "affected_D - control_D"
  affected_vs_unaffected_N: "affected_N - control_N"
  affected_vs_unaffected_E: "affected_E - control_E"
  D_vs_E_int: "(affected_D - control_D) - (affected_E - control_E)"
  D_vs_N_int: "(affected_D - control_D) - (affected_N - control_N)"
  N_vs_E_int: "(affected_N - control_N) - (affected_E - control_E)"

# Shrinkage method for DESeq2 (either "normal" or "ashr". "apeglm" not implemented)
shrinkage_method: "ashr"
# Whether plots shall be generated
plot: True
# Specify plot atributes
plot_atr:
  # Can I make this a list so it makes several PCA?
  pca: "group"
  heatmap_ann: "group"
  # Number of genes to show in the heatmap
  de_genes_n: 50

## Pathway analysis params
# Species
species: "hsapiens"
## ORA params
# Base URL
baseurl: "https://biit.cs.ut.ee/gprofiler"
# Translate gene ID to orthologous target species. False or the species.
orth_species: false
## FGSEA params
# GMT file
gmt: "/home/joan/OneDrive/UOC/TFM/testdata/Symbol2Reactome_curated.gmt"
# Gene identifier to use in the GSEA ("ENSEMBL","SYMBOL")
id_type: "SYMBOL"
# Rank column number or name ("stat","shrunkenlfc")
rank: "stat"